### PR TITLE
Random fixes and support for removing local config when using the global profile

### LINKED ISSUE #1: Remove local profile info when using 'global' profile
It would be nice if the local profile information was removed when setting the global profile.

### PR DESCRIPTION
**Pull request by zimme**
Fixes #1.

### CODE REVIEW

**Review by sramam — CHANGES_REQUESTED** [review]
@zimme, missed seeing your contribution. Sorry - just not used to other viewing my projects! Will keep a closer eye going forward.

That said, could you please also bump the version? Then I could publish the new version.

**Comment by zimme** [comment]
I've updated some dependencies now, this means that node 4+ is needed to use this package.
Bumped the package version too.

**Comment by sramam** [comment]
merged and published! Thanks much for your contribution @zimme!

**Comment by zimme** [comment]
No problem

**Pull request merged**
